### ISSUE TITLE
can this be used as just a remark plugin?

### ISSUE THREAD

**Issue by swyxio** [DSchau/gatsby-remark-code-titles#6]
its not clear if this must be inside gatsby remark or if it stands alone.. thank you

**Comment by DSchau** [comment]
It looks like [typical Remark plugins](https://github.com/remarkjs/remark-slug/blob/master/index.js#L14) are passed the AST directly--or more specifically a function that returns a function passed the AST--whereas gatsby-remark-* plugins are given [`markdownAST` as a destructured value](https://github.com/DSchau/gatsby-remark-code-titles/blob/master/src/index.js#L5).

Feel free to fork and create `remark-code-titles`, should be fairly easy! Let me know if I can help with anything!

We could then use that package like so _in_ this package:

```js
const remarkCodeTitles = require('remark-code-titles')

module.exports = ({ markdownAST }, options) => {
  return remarkCodeTitles(options)(markdownAST) // note: no idea if remark* plugins support options like this, but seems like they may
}
```

**Comment by DSchau** [comment]
I'd also take a PR making this a monorepo with e.g. Lerna (and introducing a new remark-code-titles package) -- but that's a bit more work :)

**Comment by swyxio** [comment]
aw man why isnt the gatsby remark plugin plugin api the same as the remark plugin api? then you'd have to make gatsby versions of everything lol

welp i wound up investigating and just ripped out code titles instead cos i couldnt get it to work and didnt wanna mess with ast stuff at midnight.. someday i might return to this.

its a really neat library tho! was honestly surprised it didnt exist in remark first.

is this code titles convention used anywhere else? im wondering where you got the idea from

**Comment by DSchau** [comment]
> aw man why isnt the gatsby remark plugin plugin api the same as the remark plugin api? then you'd have to make gatsby versions of everything lol

That's actually a really good question! The idea is that gatsby-remark-* plugins are no different than other plugins (so you can e.g. tie into browser APIs with gatsby-remark-autolink-headers) but `index.js` doesn't have any special significance in Gatsby and apart from these remark-* plugins, so they could've been treated similarly. The main issue would be confusion in passing pluginOptions 🤷‍♂ 

> welp i wound up investigating and just ripped out code titles instead cos i couldnt get it to work and didnt wanna mess with ast stuff at midnight.. someday i might return to this.

Let me know if you do! It's really 5-10 minutes of work to get the plugin published/working!

> is this code titles convention used anywhere else? im wondering where you got the idea from

I think I saw it _somewhere_ (no idea where!) and wondered if I could do it in Gatsby, and here we are!

**Comment by swyxio** [comment]
gotcha. i'll be honest i'm not gonna get to publishing a remark-code-titles anytime soon since i already took it out of my own markdown. just a TODO i guess. good to know you think its easy, if i ever need it again i may take you up on this
